### ISSUE TITLE
Model creation error: model value required

### ISSUE THREAD

**Issue by eduhdev12** [bartventer/gorm-multitenancy#10] opened 2024-04-25 22:21 UTC
### Describe the bug
Following the provided informaton from the main `README` and the router middleware examples with the book routes, I can't create any new book, getting the error `model value required`

### To Reproduce
1. Create the chi router
2. Create the models and init the multi-tenancy
3. Create the `create-book` route

## Expected behavior
To create the database entry without any issues

### Version
Which version(s) of the `gorm-multitenancy` modules are you seeing the bug with?
v1.0.9 (latest)

**Comment by bartventer** [comment] 2024-04-26 07:04
Thank you for your report. It seems you're using an outdated version (v1.0.9) of the module. Please update to the latest version (v5) using:

```bash
go get -u github.com/bartventer/gorm-multitenancy/v5
```

If the issue persists, provide detailed steps to reproduce it, including your exact code.

Also, while the README provides useful snippets, the full [PostgreSQL with net/http](https://github.com/bartventer/gorm-multitenancy/tree/master/internal/examples/nethttp) example in the repository might give you a more comprehensive understanding of how to use the module. If you haven't already, I recommend checking it out.

**Comment by eduhdev12** [comment] 2024-04-26 10:32
Sorry, the version was the latest (v5)
But, in the documentation [See here](https://github.com/bartventer/gorm-multitenancy/blob/master/internal/examples/nethttp/main.go#L316) the transaction should begin with the table, right?

Example:
```
tx := db.Begin().Table("books")
```

With Table after begin it's working without any issues for me

**Comment by bartventer** [comment] 2024-04-26 11:02
Could you please provide the full code you're running?

Also, I just updated all the examples to simply the usage. Make sure you're using the [latest version of the examples](https://github.com/bartventer/gorm-multitenancy/tree/master/examples). If you're still encountering issues with the updated examples, please let me know.

**Comment by shinusuresh** [comment] 2024-06-02 20:10
Getting the same error that is reported above using 6.1.1
I am using this example - https://github.com/bartventer/gorm-multitenancy/blob/master/examples/echo/main.go

```
curl -X POST -H "X-Tenant: tenant2" http://localhost:8080/books                                                                                    ✔  took 43s
{"message":"model value required"}
```

**Comment by bartventer** [comment] 2024-06-02 21:35
@shinusuresh, thank you for the repro. The issue was due to the Book struct using a pointer receiver for its TenantTabler implementation. I've updated the example to fix this.

Please update to the latest version with:
```go
go get -u github.com/bartventer/gorm-multitenancy/v6@v6.1.2
```

If you encounter further issues, please let me know. For now, I'm marking this as resolved.

**Closed by bartventer** 2024-06-02 21:35 UTC

**Comment by shinusuresh** [comment] 2024-06-02 22:29
Thanks @bartventer
